### PR TITLE
Update excerpt logic to (almost) the latest SDK and packages

### PR DESCRIPTION
**Pull request by kevmoo**
* Add GitHub Actions (CI)
* Enable and fix a bunch of lints

### CODE REVIEW

**Comment by RedBrogdon** [comment]
LGTM, as long as @kwalrath and @sfshaza2 are cool with this repo having CI set up (it should, since there are now packages maintained here, but I wouldn't want to spring this on them unawares).

**Review by RedBrogdon — APPROVED** [review]

**Comment by mit-mit** [comment]
Why is this actually in `site-shared`? Is it used anywhere else than `site-www` ?

**Review by kwalrath — APPROVED** [review]

**Comment by kwalrath** [comment]
> Why is this actually in `site-shared`? Is it used anywhere else than `site-www` ?

I believe that flutter.dev is using the code excerpter more and more.

**Comment by chalin** [comment]
Nice to see that the tools have a new home! ✨

**Pull request merged**
