### PR TITLE
added section to direct Linux users to modify the PATH variable.

### LINKED ISSUE #37: Add path info to Dart SDK page
_From @oneyb on August 31, 2018 16:14_

From URL: https://webdev.dartlang.org/tools/sdk/

It would be good to include complete installation information. This means adding the sdk directory to the PATH. #19926 

You know after installing the binaries:

```bash
echo 'export PATH="/usr/lib/dart/bin:$PATH"' >> $HOME/.profile
```

_Copied from original issue: dart-lang/site-webdev#1812_

### PR DESCRIPTION
**Pull request by oneyb**
I think I got this commit right.

Should help alleviate problems related to dart-lang/sdk#19926 and fixes #37

### CODE REVIEW

**Comment by kwalrath** [comment]
Don't we need to set the PATH no matter whether you use apt-get or Debian? Maybe we should have something like this:

----------

image

----------

**Comment by kwalrath** [comment]
@oneyb are you OK with my change?

**Comment by chalin** [comment]
@kwalrath, I like your suggested change, but I'd recommend either not giving a bash command (i.e., just stating "set your path"), or using another bash command (since the given command isn't setting the path, it is updating the profile).

If you prefer that there be a command, how about the usual:

```console
$ export PATH="$PATH:/usr/lib/dart/bin"
```

(Also, can you get someone on the team to confirm that `/usr/lib/dart/bin` is the correct path under Linux?)

**Comment by oneyb** [comment]
@kwalrath I am really sorry for the delay. I was not aware that the ball was in my court. Yes, your change looks good. apt or dpkg will install the package to the same directory, as the .deb file instructs.

@chalin I have installed dart using the instructions and thus have everything here: /usr/lib/dart/bin/

``` shell
$ ls -al /usr/lib/dart/bin/
total 27384
drwxr-xr-x 3 root root     4096 Aug 14 20:34 .
drwxr-xr-x 5 root root     4096 Aug 14 20:34 ..
-rwxr-xr-x 1 root root 27998864 Aug  3 11:19 dart
-rwxr-xr-x 1 root root     1481 Aug  3 11:19 dart2js
-rwxr-xr-x 1 root root      953 Aug  3 11:19 dartanalyzer
-rwxr-xr-x 1 root root      944 Aug  3 11:19 dartdevc
-rwxr-xr-x 1 root root      970 Aug  3 11:19 dartdevk
-rwxr-xr-x 1 root root      975 Aug  3 11:19 dartdoc
-rwxr-xr-x 1 root root      915 Aug  3 11:19 dartfmt
-rwxr-xr-x 1 root root     1345 Aug  3 11:19 pub
drwxr-xr-x 3 root root     4096 Aug 14 20:34 snapshots
```
I am using Debian 9 (Stretch).

It would not be bad to include both commands. Something like:

``` shell
# For persistent PATH modification, use:
echo 'export PATH="$PATH:/usr/lib/dart/bin"' >> ~/.profile
# In order to change the PATH for a single session, use:
export PATH="$PATH:/usr/lib/dart/bin"
```
Does that look better?

**Comment by chalin** [comment]
Thanks for confirming @oneyb.

> It would not be bad to include both commands.

I'm generally hesitant to instruct folks on how to persist PATH changes because advanced users will ignore the command (and do whatever they usually do), and and newbies will be unaware of the potentially subtle consequences of the specific command we are recommending (e.g., I'd usually recommend updating `.bash_profile`, but that assumes the reader is using bash). If we don't give a specific command, then newbies are left with searching elsewhere -- like on Stackoverflow, where they can get more context.

That being said, I'm ok with what you suggest, possibly tweaked as follows:

> After installing the SDK, **add its `bin` directory to your `PATH`**. For example,
> use this command to change `PATH` in your active terminal session:
>
> ```console
> $ export PATH="$PATH:/usr/lib/dart/bin"
> ```
> 
> To persist the `PATH` change for future terminal sessions, use a command like this:
> 
> ```console
> $ echo 'export PATH="$PATH:/usr/lib/dart/bin"' >> ~/.profile
> ```

**Comment by chalin** [comment]
@kwalrath WDYT about the prose suggested in the previous comment?

**Comment by kwalrath** [comment]
I'm fine with your prose, @chalin. @oneyb are you willing and able to make this change?

**Comment by kwalrath** [comment]
Although I'd tweak the text (of course) to avoid using "persist". Maybe:

To reuse this `PATH` in future terminal sessions, save it to a shell initialization file like this:

**Comment by kwalrath** [comment]
Thanks, @oneyb! I'm checking the built version now...

**Comment by kwalrath** [comment]
We have a CSS style issue that makes the `>>` invisible (see the second snippet, below). I don't think that should stop this PR, since you can select the code to see it. I'll file an issue.

image

**Comment by oneyb** [comment]
One could use tee instead. 

```terminal
echo text | tee -a ~/.profile
```

**Comment by chalin** [comment]
@kwalrath - I'll fix the CSS issue (which, I believe, we've fixed on the Flutter side already). Do you want to merge first and then I'll update the CSS?

**Comment by kwalrath** [comment]
Yes, please, @chalin. Thanks for the `tee` workaround, @oneyb, but the CSS fix is something we'd need to do anyway.

**Pull request merged**
