### PR TITLE
added the wiki pages to doc folder

### PR DESCRIPTION
**Pull request by sidx8**

### CODE REVIEW

**Comment by sidx8** [comment]
here I added hyphens and changed them to lowercase

**Comment by kwalrath** [comment]
The pages' filenames still need to be updated. So Images.md -> images.md, Mobile-friendly-pages-tips-&-tricks.md -> mobile-friendly-pages.md, and Writing-for-Dart-and-Flutter-websites.md -> writing-for-dart-and-flutter-websites.md.

**Comment by sidx8** [comment]
sorry I took a lot of time but here I changed the file name to lowercase

**Comment by sidx8** [comment]
is there any other work left to do in this issue

**Comment by kwalrath** [comment]
I think it's done. I'll merge this, and then we can see what remains.

**Pull request merged**
