### PR TITLE
Add support for new Dart features to prettify

### PR DESCRIPTION
**Pull request by parlough**

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]

**Comment by kevmoo** [comment]
Weird this is not coordinated (in some way) with https://github.com/dart-lang/dart-syntax-highlight

Right?

**Comment by kevmoo** [comment]
CC @devoncarew

**Comment by parlough** [comment]
Because we hope to discontinue use of Prettify soon, as the library is no longer supported by Google and we already use another highlighting system on the site.

I just haven't had the chance to sit down and do it yet: https://github.com/dart-lang/site-www/issues/3846

**Comment by kevmoo** [comment]
Good to know! Thanks @parlough

**Pull request merged**
