### PR TITLE
Adding Vale to shared components for testing

### PR DESCRIPTION
**Pull request by atsansone**
Replaces https://github.com/dart-lang/site-www/pull/4231/

### CODE REVIEW

**Review by parlough — CHANGES_REQUESTED** [review]
Two concerns that will make this easier to review once addressed:

1. I'd prefer we not use the top-level `/styles` directory, as it can easily be mistaken for site styles. Consider something like `/tool/vale/styles`. https://vale.sh/docs/topics/config/#stylespath seems to have docs on configuring it. The `ini` file is fine in the root directory though.

2. I don't think we should check in the styles from third-party packages. It increases the size of the repo, has licensing concerns, and it's harder to tell what styles are custom or from packages. Consider adding a `.gitignore` file within the new `/styles` directory location that ignores all directories containing files not maintained by us.

Let me know if you have any concerns or issues with these changes though. Thanks!

**Comment by atsansone** [comment]
@parlough : Agreed on moving directories. Makes sense.

As for removing all styles not maintained by us, that would leave us with nothing. I want to merge this to be able to validate all of the Google styles as correct. They look to be correct with supporting links, but I want to be sure.

**Comment by parlough** [comment]
Thanks for moving the directory! You'll also need to change that setting in the `.vale.ini` file: https://vale.sh/docs/topics/config/#stylespath

> As for removing all styles not maintained by us, that would leave us with nothing.

If we keep them in the repo though, we would need to make sure we account for each package's license. According to [Packages and VCS](https://vale.sh/docs/topics/packages/#packages-and-vcs) on the Vale docs, it seems intended to not upload them and include them in the `gitignore`. It seems then each user that wants to use the Vale setup, will run `vale sync` locally, or rely on their editor's extension for doing so.

**Comment by atsansone** [comment]
@parlough : Good guidance! I'll make those changes today.

**Comment by atsansone** [comment]
@parlough : PTAL

**Review by parlough — APPROVED** [review]
Thanks for making those adjustments!

I haven't tried this out yet, but I think this should be good to land for us to start trying out.

**Pull request merged**
