### PR TITLE
Rename container to be more generic

### PR DESCRIPTION
**Pull request by drewroengoogle**
* Change the container/image to have a more generic name, as we can use it in other places besides website staging
* Update the readme to reflect this change
* Change the directory

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

### CODE REVIEW

**Review by khanhnwin — APPROVED** [review]

**Comment by khanhnwin** [comment]
I don't have approval permissions for this repo. Halp @parlough? Thank you!

**Review by parlough — APPROVED** [review]
I don't have the full context, but looks good to me :)

**Comment by drewroengoogle** [comment]
> I don't have the full context, but looks good to me :)

The context is that we realized we are currently building two separate containers that both are used for deploying to firebase, and this one is able to cover both of those cases, meaning we don't have to make updates in two places if we want a new version of firebase-tools. I just wanted to change the naming for clarity

**Comment by parlough** [comment]
Less duplication sounds great to me!

Maybe you have already, but you should also check in with Dart EngProd as I think they might want to migrate the Dart specification deployment as well :)

**Pull request merged**
